#ifndef DTOOL_COMMON_H_INCLUDED
#	define DTOOL_COMMON_H_INCLUDED 1

#	define DTOOL_STR_HELPER(parameter)#parameter
#	define DTOOL_STR(parameter) DTOOL_STR_HELPER(parameter)
#	define DTOOL_VERSION_MAJOR 1
#	define DTOOL_VERSION_MINOR 0
#	define DTOOL_VERSION_PATCH 0
#	define DTOOL_VERSION DTOOL_STR(DTOOL_VERSION_MAJOR) "." DTOOL_STR(DTOOL_VERSION_MINOR) "." DTOOL_STR(DTOOL_VERSION_PATCH)

#endif
